server:
  port: 3344

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Huang-siyuan/SOAConfigServer.git
          search-paths:
            - SOAConfigServer
          default-label: main


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
