server.port=8002
spring.application.name=SOA-SECOND-SERVICE
#spring.datasource.username=s284200
#spring.datasource.password=123456

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/soa
#spring.datasource.url=jdbc:postgresql://pg:5432/studs
spring.datasource.username=postgres
spring.datasource.password=123456


#server.ssl.key-store=C:/Users/TheHs/IdeaProjects/SOA_Service_2/second-service-2/src/main/resources/keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=lab.jks

eureka.client.register-with-eureka=true
eureka.client.fetchRegistry=true
eureka.client.service-url.defaultZone=http://localhost:7001/eureka/
eureka.instance.instance-id=second-service-2
eureka.instance.prefer-ip-address=true
